// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8UOEyesjxbaZnfg2LQm09y7SieQ6Qv3o',
    appId: '1:425853628516:web:b24678bbf4846a76352f71',
    messagingSenderId: '425853628516',
    projectId: 'fluapp-1343e',
    authDomain: 'fluapp-1343e.firebaseapp.com',
    storageBucket: 'fluapp-1343e.appspot.com',
    measurementId: 'G-C3WTBNZXP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs3IQRluV1Ckd1TPQH8Yckan8Bxz82zxI',
    appId: '1:425853628516:android:bbaaf238a4ad3146352f71',
    messagingSenderId: '425853628516',
    projectId: 'fluapp-1343e',
    storageBucket: 'fluapp-1343e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyB8j_N_bK_bEky-SkiUoTQvWJzGWwsL4',
    appId: '1:425853628516:ios:9fe8b27111c560cd352f71',
    messagingSenderId: '425853628516',
    projectId: 'fluapp-1343e',
    storageBucket: 'fluapp-1343e.appspot.com',
    iosClientId: '425853628516-n6ejrphmvbodh71qkmvuokr92p14kv48.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
